### ISSUE TITLE
In non-development environments, don't try to run `make .env`.

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-makefile#128]
I think I understand n-makefile a little better now. 

**A.** CircleCI does a build step: "Exporting env vars from project settings", whereby the heroku environment is populated with appropriate environment values.
![image](https://cloud.githubusercontent.com/assets/224547/21773610/ad8652a6-d687-11e6-92bd-53d7744e840b.png)

**B.** As a developer, the equivalent is to generate and save a local `.env` file, which is used to do the same thing. 

It's not a good idea to save our environment variables in the heroku instances generated by CircleCI (or in any environments other than trusted developers local machines). And anyway, `.env` is not needed because of the "Exporting env vars" step. So: _In non-development environments, don't try to run `make .env`._ 

The way this was previously achieved is in this commit:  https://github.com/Financial-Times/n-makefile/commit/b4c4f675dafd2c50f119d9cc18272dd31c89b21a But I changed that logic in [this pull request](https://github.com/Financial-Times/n-makefile/pull/127) because it was difficult debugging a problem with expecting a certain value to exist in the `.gitignore` file. I broke one line apart into three guardians. 

### Get to the point 

Okay. So here's the current problem:

![image](https://cloud.githubusercontent.com/assets/224547/21772559/bdf1eb0e-d683-11e6-9695-2b0fcbc34bf9.png)

The error's occurring because `make .env` is being invoked. 

**Solution one** could be: Refrain from erroring (output a notice or something) and continue running the script. But the reason I got involved in the first place was because it was not erroring for the .gitignore failure, leading to me puzzled as to why `make .env` was not erroring, and yet also not generating the expected `.env` file. Maybe a non-failing notice would suffice there but it's better to halt the execution of the script.

So, **solution two** is preferable: Find out whatever's calling `make .env` and add some logic to make it only run on developers' machines. And consider changing it so that a developer must actually execute `make .env` themselves, rather than doing it automagically.

Yes? No? Please comment! Thanks.

**Comment by adambraimbridge** [comment]
Update: I've tested this by manually updating n-Makefile here: https://github.com/Financial-Times/next-mission-control/commit/839029d2c7d5a183854722a5f5ef503e7f090305

It is now passing the build because `make install` no longer invokes the `.env` target. So circleCI can run `make install` with impunity. 

Todo: Update `make install` that, when appropriate, prompts developers to execute `make .env`.

**Comment by adambraimbridge** [comment]
@wheresrhys @sjparkinson Update: There's a tricky problem.

It turns out that `sinclude .env` is actually required, otherwise the environment variables are not exported. `make run` fails at the first instance of an environment variable being required.

![image](https://cloud.githubusercontent.com/assets/224547/21813822/56072c3a-d74f-11e6-98bc-fdd52899e44b.png)

But `sinclude .env` invokes the `.env` make target, which should not be invoked automatically. 

I'll try: 
(a) move `sinclude .env` into the `run` target, or 
(b) wrap  `sinclude .env` to make sure it only runs if the .env file exists. (Assuming that will stop it from invoking .env ...)

**Comment by sjparkinson** [comment]
The great make learning adventure. :tm:

**Comment by adambraimbridge** [comment]
http://www.oreilly.com/openbook/make3/book/ch12.pdf 😱

**Comment by adambraimbridge** [comment]
Update: It looks like environment vars are exported from the .env file by n-heroku-tools. 

https://github.com/Financial-Times/n-heroku-tools/blob/master/lib/keys.js#L11

Removing the line in Makefile that tries to do the same thing actually makes the error go away.

![image](https://cloud.githubusercontent.com/assets/224547/21815972/517098f8-d756-11e6-83bc-2385951e6cb8.png)

Passes in CircleCI too: https://circleci.com/gh/Financial-Times/next-mission-control/77

I wish debugging this was easier.

**Comment by adambraimbridge** [comment]
I made a PR for option (c): Don't export environment variables from the local .env file.

**Comment by adambraimbridge** [comment]
All sorted.
