### ISSUE TITLE
n-ui test for components fails when n-ui is only used in 1 of either bower or package.json

### ISSUE THREAD

**Issue by debugwand** [Financial-Times/n-makefile#162]
n-concept and n-image don't have n-ui in both bower and package.json, so the test for versions fails, so therefore they cannot yet upgrade from v1 of n.Makefile. The test should check to see if both exist before comparing versions

**Comment by adambraimbridge** [comment]
See: https://circleci.com/gh/Financial-Times/n-concept/88
```bash
awk: fatal: cannot open file `node_modules/@financial-times/n-ui/package.json' for reading (No such file or directory)
make[1]: Entering directory `/home/ubuntu/n-concept'
n.Makefile:96: *** 'Projects using n-ui must maintain parity between versions. Rebuild without cache and update your bower.json and package.json if necessary'.  Stop.
```

**Comment by adambraimbridge** [comment]
Boy oh boy, this opened up a yak-shavin' can of rabbit holes. 

The short story: @debugwand Is going to try converting n-concept to the n-ui way of doing demos. 

Stay tuned.
