### ISSUE TITLE
Error when pulling config-vars

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/n-makefile#68]
```
Cannot get config vars for this service.  Check you are added to the ft-next-config-vars service on Heroku with operate permissions.  Do that here - https://docs.google.com/spreadsheets/d/1mbJQYJOgXAH2KfgKUM1Vgxq8FUIrahumb39wzsgStu0 (or ask someone to do it for you).  Check that your package.json's name property is correct.  Check that your project has config-vars set up in models/development.js.
make: *** [.env] Error 1
```

Next-ads-component doesn't have any environment variables. So I feel like this shouldn't necessarily be an error? Maybe put up a warning making it clear it hasn't got them and that it might because of one of these reasons.

**Comment by matthew-andrews** [comment]
just remove `.env` from your `.gitignore` file and then it won't download it.

**Comment by leggsimon** [comment]
Would that not be a worry if we added some and it was inadvertently pushed?

**Comment by leggsimon** [comment]
Actually no I guess it would just have to be changed in config-vars
