### ISSUE TITLE
Extract webpack into its own component

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-makefile#91]
When it comes to building multiple js bundles, some of which may need to communicate with each other, it’s necessary to use slightly different webpack.config.js files. Also, another use case is to generate a normal bundle (as we have now) as well as another that utilises a shared bundle, so that if there’s a problem with the shared bundle experiment at least the full bundle exists and can be switched back to with a flag.

So I’m thinking of creating n-webpack, which
a) installs all the webpack dependencies
b) exports some functions that can be used to generate a webpack config
c) export a cli task `nwebpack —config path/to/config/file` (default to webpack.config.js)
d) n-makefile will contain a webpack.config.js file which requires bits and pieces from n-webpack
e) probably rename n-makefile.json to n-webpack.json (but keep it backwards compatible)

**Comment by bjfletcher** [comment]
Can you explain more how we'd create the shared bundles across apps?  I'll be in a better position to respond once I've understood this.

Just one thing regarding your list:

> e) probably rename n-makefile.json to n-webpack.json (but keep it backwards compatible)

:-1: Node app (not Webpack) may use information in `n-makefile.json` to render UI views.

**Comment by wheresrhys** [comment]
done
